# Board, Bootloader and MCU
MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = yes
#COMMAND_ENABLE = yes
BOOTMAGIC_ENABLE = yes

ENCODER_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes
EXTRAKEY_ENABLE = yes       # Audio control and System control
NKRO_ENABLE = yes

OPT_DEFS += -DHAL_USE_I2C=TRUE